# Choose different file in the .env file
# "dev" for development only NOT TO PROD!!!
# Effect on the logger and other settings...
env: "dev" # Environment name: local, dev, prod
http-server:
  address: "localhost:8081"
  read-timeout: 10s
  write-timeout: 10s
  idle-timeout: 60s
  shutdown-timeout: 5s
  access-token-ttl: 10m
  refresh-token-ttl: 24h
db:
  host: "localhost"
  port: 5432
  name: "test-task1"