env: "local"
http_server:
  address: "localhost:8081"
  read-timeout: 10s
  write-timeout: 10s
  idle_timeout: 60s
  access-token-ttl: 1h
  refresh-token-ttl: 24h
db:
  host: "localhost"
  port: 5432
  name: "test-task1"