env: "local"
http-server:
  address: "localhost:8081"
  read-timeout: 10s
  write-timeout: 10s
  idle-timeout: 60s
  access-token-ttl: 10m
  refresh-token-ttl: 24h
db:
  host: "localhost"
  port: 5432
  name: "test-task1"