# Choose different file in the .env file
# "local" for local development only NOT TO PROD!!!
env: "local" # Environment name: local, dev, prod
http-server:
  address: "localhost:8081"
  read-timeout: 10s
  write-timeout: 10s
  idle-timeout: 60s
  shutdown-timeout: 5s
  access-token-ttl: 10m
  refresh-token-ttl: 24h
db: #password in .env
  host: "localhost"
  port: 5432
  name: "test-task1"
cache: #password in .env
    host: "localhost"
    port: 6379
    db-index: 0
    ttl: 10m